apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qar.applicationName" . }}-pod-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "qar.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "qar.applicationName" . }}-pod-reader
subjects:
- kind: ServiceAccount
{{- if empty .Values.global.existingServiceAccount }}
  name: {{ include "qar.applicationName" . }}
{{- else }}
  name: {{ .Values.global.existingServiceAccount }}
{{- end }}
  namespace: {{ .Release.Namespace | quote }}
