{{- $dbUserDelegated := .Values.db.auth.usernameSource.useSecret -}}
{{- $dbPassDelegated := .Values.db.auth.passwordSource.useSecret -}}
{{- $odUserDelegated := .Values.auth.usernameSource.useSecret -}}
{{- $odPassDelegated := .Values.auth.passwordSource.useSecret -}}
{{- $zkUserDelegated := .Values.zookeeper.auth.usernameSource.useSecret -}}
{{- $zkPassDelegated := .Values.zookeeper.auth.passwordSource.useSecret -}}
{{- $loadUserDelegated := .Values.arsload.auth.usernameSource.useSecret -}}
{{- $loadPassDelegated := .Values.arsload.auth.passwordSource.useSecret -}}
{{- $restUserDelegated := .Values.restapi.auth.usernameSource.useSecret -}}
{{- $restPassDelegated := .Values.restapi.auth.passwordSource.useSecret -}}
{{- $odUser := .Values.auth.username | default "archive" -}}
{{- $odPass := .Values.auth.password | default (randAlphaNum 30) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qar.fullname" . }}-ondemand
  namespace: {{ include "qar.namespace" . | quote }}
  labels: {{- include "qar.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ondemand
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  pdbArchiveName: {{ .Values.serverInstanceName | default "archive" | lower | b64enc }}
{{- if not .Values.db.auth.usernameSource.useSecret }}
  dbUsername: {{ .Values.db.auth.username | default "archive" | b64enc }}
{{- end }}
{{- if not .Values.db.auth.passwordSource.useSecret }}
  dbPassword: {{ .Values.db.auth.password | default (randAlphaNum 30) | b64enc }}
{{- end }}
{{- if not .Values.auth.usernameSource.useSecret }}
  odUsername: {{ .Values.auth.username | default "archive" | b64enc }}
{{- end }}
{{- if not .Values.auth.passwordSource.useSecret }}
  odPassword: {{ $odPass | b64enc }}
{{- end }}
{{- if .Values.zookeeper.enabled }}
  {{- if not .Values.zookeeper.auth.usernameSource.useSecret }}
  zkUsername: {{ .Values.zookeeper.auth.username | default "archive" | b64enc }}
  {{- end }}
  {{- if not .Values.zookeeper.auth.passwordSource.useSecret }}
    {{- if and (not .Values.auth.passwordSource.useSecret) (and (not .Values.zookeeper.auth.usernameSource.useSecret) (not .Values.auth.usernameSource.useSecret)) }}
      {{- if eq $odUser ( .Values.zookeeper.auth.username | default "archive" ) }}
  zkPassword: {{ $odPass | b64enc }}
      {{- end }}
    {{- end }}
  {{- else }}
  zkPassword: {{ .Values.zookeeper.auth.password | default (randAlphaNum 30) | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.arsload.enabled }}
  {{- if not .Values.arsload.auth.usernameSource.useSecret }}
  username: {{ .Values.arsload.auth.username | default "archive" | b64enc }}
  {{- end }}
  {{- if and (not .Values.auth.passwordSource.useSecret) (not .Values.arsload.auth.passwordSource.useSecret) }}
    {{- if and (not .Values.auth.usernameSource.useSecret) (not .Values.arsload.auth.usernameSource.useSecret) }}
      {{- if eq $odUser ( .Values.arsload.auth.username | default "archive" ) }}
  password: {{ $odPass | b64enc }}
      {{- end }}
    {{- end }}
  {{- else if not .Values.arsload.auth.passwordSource.useSecret }}
  password: {{ .Values.arsload.auth.password | default (randAlphaNum 30) | b64enc }}
  {{- end }}
{{- end }}
{{- if.Values.restapi.enabled }}
  {{- if not .Values.restapi.auth.usernameSource.useSecret }}
  restUsername: {{.Values.restapi.auth.username | default "archive" | b64enc }}
  {{- end }}
  {{- if and (not .Values.auth.passwordSource.useSecret) (not .Values.restapi.auth.passwordSource.useSecret) }}
    {{- if and (not .Values.auth.usernameSource.useSecret) (not .Values.restapi.auth.usernameSource.useSecret) }}
      {{- if eq $odUser (.Values.restapi.auth.username | default "archive") }}
  restPassword: {{ $odPass | b64enc }}
      {{- end }}
    {{- end }}
  {{- else if not .Values.restapi.auth.passwordSource.useSecret }}
  restPassword: {{ .Values.restapi.auth.password | default (randAlphaNum 30) | b64enc }}
  {{- end }}
{{- end }}
