apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" .}}
  labels:
    {{ include "registry.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.secrets.htpasswd }}
  htpasswd: {{ .Values.secrets.htpasswd | b64enc | quote }}
{{- end}}
  haSharedSecret: {{ .Values.secrets.haSharedSecret | default (randAlphaNum 16) | b64enc | quote }}
