{{- if .Values.restapi.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qar.applicationName" . }}-ondemand-restapi
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "qar.labels" . | nindent 4 }}
  {{- with .Values.restapi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.restapi.ingress.tls }}
  tls:
  {{- range .Values.restapi.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.restapi.ingress.host }}
    http:
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            serviceName: {{ include "qar.applicationName" . }}-ondemand-restapi
            servicePort: {{ .Values.global.ondemand.portOverride | default 9080 }}
{{- end }}
