{{- $passwordDelegated := eq (include "qar.secret.isDelegated" .Values.global.ondemand.passwordOverrideSource) "true" }}
{{- $userDelegated := eq (include "qar.secret.isDelegated" .Values.global.ondemand.userOverrideSource) "true" }}
{{- $onDemandDatabaseSecretName :=  printf "%s-%s-database" (include "qar.applicationName" . ) "ondemand" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $onDemandDatabaseSecretName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qar.applicationName" . }}-oracledb-setup
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "qar.labels" . | nindent 4 }}
data:
  01-create-archive-pdb.sql: |
    CREATE PLUGGABLE DATABASE {{ $secret.pdbArchiveName }}
    ADMIN USER {{ $secret.username }} IDENTIFIED BY {{ $secret.password }}
    FILE_NAME_CONVERT=('/opt/oracle/oradata/ORCLCDB/pdbseed','/opt/oracle/oradata/ORCLCDB/archive');
  02-open-archive-pdb.sql: |
    ALTER PLUGGABLE DATABASE {{ $secret.pdbArchiveName }} OPEN READ WRITE;
  03-save-archive-pdb.sql: |
    ALTER PLUGGABLE DATABASE {{ $secret.pdbArchiveName }} SAVE STATE;
  04-create-navigator-pdb.sql: |
    CREATE PLUGGABLE DATABASE navigator
    ADMIN USER {{ $secret.username }} IDENTIFIED BY {{ .Values.password }}
    FILE_NAME_CONVERT=('/opt/oracle/oradata/ORCLCDB/pdbseed','/opt/oracle/oradata/ORCLCDB/navigator');
  05-open-navigator-pdb.sql: |
    ALTER PLUGGABLE DATABASE navigator OPEN READ WRITE;
  06-save-navigator-pdb.sql: |
    ALTER PLUGGABLE DATABASE navigator SAVE STATE;
  07-archive-grant-perms.sql: |
    ALTER SESSION SET CONTAINER = {{ $secret.pdbArchiveName }};

    --
    -- Create Content Manager OnDemand role : ONDEMAND
    --
    DROP ROLE ONDEMAND;
    CREATE ROLE ONDEMAND;
    -- Database
    grant SELECT ANY DICTIONARY to ONDEMAND;
    -- Session
    grant CREATE SESSION to ONDEMAND;
    -- Tablespaces
    grant CREATE TABLESPACE to ONDEMAND;
    grant DROP TABLESPACE to ONDEMAND;
    -- Tables
    grant ALTER ANY TABLE to ONDEMAND;
    grant BACKUP ANY TABLE to ONDEMAND;
    grant CREATE TABLE to ONDEMAND;
    grant DELETE ANY TABLE to ONDEMAND;
    grant DROP ANY TABLE to ONDEMAND;
    grant INSERT ANY TABLE to ONDEMAND;
    grant LOCK ANY TABLE to ONDEMAND;
    grant SELECT ANY TABLE to ONDEMAND;
    grant UPDATE ANY TABLE to ONDEMAND;
    -- Indexes
    grant CREATE ANY INDEX to ONDEMAND;
    grant DROP ANY INDEX to ONDEMAND;

    --
    -- Grant role & permissions to ARCHIVE user
    ---
    grant ONDEMAND to ARCHIVE;
    grant UNLIMITED TABLESPACE to ARCHIVE;
