{{- if (include "docuhost.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docuhost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "docuhost.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.db.username | b64enc | quote }}
  db-password: {{ .Values.db.password | b64enc | quote }}
{{- end  }}
