apiVersion: v1
kind: Service
metadata:
  name: {{ include "docuhost.fullname" . }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
      name: http
  selector: {{- include "docuhost.selectorLabels" . | nindent 4 }}
