{{- if (include "interactive.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interactive.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "interactive.labels" . | nindent 4 }}
type: Opaque
data:
  cx-lic-server: {{ required "A value for 'inspireLicenseServer' is required." .Values.inspireLicenseServer | b64enc | quote }}
  db-password: {{ required "A value for 'databasePassword' is required." .Values.databasePassword | b64enc | quote }}
  db-user: {{ required "A value for 'databaseUser' is required." .Values.databaseUser | b64enc | quote }}
  icm-password: {{ required "A value for 'icmPassword' is required." .Values.icmPassword | b64enc | quote }}
  icm-user: {{ required "A value for 'icmUser' is required." .Values.icmUser | b64enc | quote }}
{{- end  }}