image:
  # -- Defines the URL address of the ICM image stored in a Docker image repository.
  name: ""
  # -- Defines a specific version of the ICM image to be deployed.
  tag: ""
  # -- Defines the ICM image pull policy. [IfNotPresent/Always]
  pullPolicy: IfNotPresent

# -- Defines an array of volumes to be mounted to the ICM pod.
# For example, you may need to mount a Container Storage Interface (CSI) volume to pass Secrets to Kubernetes from an external secret management system (e.g. AWS Secrets Manager).
volumes: []
# The following commented object is an example of a CSI volume:
# - name: my-csi-storage
#   csi:
#     driver: secrets-store.csi.k8s.io
#     readOnly: true
#     volumeAttributes:
#       secretProviderClass: "my-secret-provider"

# -- Creates an Init Container that will mount the given volumes to the application pod.
# It also instructs the CSI driver to create Kubernetes Secrets from Secrets stored in external storage (e.g. AWS Secrets Manager).
# It uses the 'SecretProviderClass' definition to manage the Secret synchronization.
activateVolumes:
  # -- Defines whether or not to create the Init Container.
  enabled: false
  # -- Defines an array of volumes to be mounted.
  volumes:
    - name: my-csi-storage

db:
  # -- Defines the hostname of the server that runs the database.
  host: ""
  # -- Defines the port of the server that runs the database.
  port: ""
  # -- Defines (in plain text) the username of the database user.
  # Use the 'userSource' variable instead if you wish to define the username using a Secret.
  user: ""
  # -- Available since the 15.0 GA version of ICM.
  # Uses a Secret to define the username of the database user.
  userSource:
    useSecret: false
    secretName: ""
    secretKey: ""
  # -- Defines (in plain text) the password of the database user.
  # Use the 'passSource' variable instead if you wish to define the password using a Secret.
  pass: ""
  # -- Available since the 15.0 GA version of ICM.
  # Uses a Secret to define the password of the database user.
  passSource:
    useSecret: false
    secretName: ""
    secretKey: ""
  # -- Defines the name of an existing database that will be used.
  name: ""
  # -- Defines the type of your database. [PostgreSql/Oracle/MsSql/MicrosoftSQL/SQLAzure/MySql/DB2]
  type: ""
  # -- Defines (in plain text) a custom connection string to connect to the database.
  # Use the 'connectionStringSource' variable instead if you wish to define the connection string using a Secret.
  connectionString: ""
  # -- Available since the 15.0 GA version of ICM.
  # Uses a Secret or a Volume to define a custom connection string to connect to the database.
  connectionStringSource:
    useSecret: false
    secretName: ""
    secretKey: ""
  # -- Allows you to customize the database connection if you use the standard database connection settings (e.g. host, port etc.).
  connectionStringAdd: ""

# -- Defines the number of replicas to be created after deployment.
replicaCount: 1
# -- Defines how long (in seconds) Kubernetes should wait before shutting down the pod.
shutdownTimeout: 90

# -- Defines whether you wish to import a package into ICM using a Kubernetes pattern for importing big data.
# Build a docker image containing the ICM package you wish to import.
# The container starts as an init container and its init script copies and renames the package to /opt/import/initialIcmData.pkg.
useInitImport: false
initImport:
  image:
    # -- Defines the URL address of the ICM package image stored in a Docker image repository.
    name: ""
    # -- Defines a specific version of the ICM package image to be deployed.
    tag: ""
    # -- Defines the ICM package image pull policy. [IfNotPresent/Always]
    pullPolicy: IfNotPresent

# -- Defines ICM commands for running as an application.
# For example, the -allowdatarecording command is necessary for Scaler's data recording feature.
addParams: ""

# -- Defines a configuration to be created in the InspireICM.config file.
# For example: <AllowedDirectories></AllowedDirectories>.
# The ConnectionString method must be used along with configFileContent because a mounted file becomes readonly and ICM cannot write into it.
configFileContent: ""

externalAccess:
  # -- Since the 15.0 version, this feature allows you to configure ICM to run an HTTPS server. Clients can connect to ICM using the HTTPS protocol.
  # If you enable 'externalAccess', you must also configure the 'ingress' settings.
  enabled: false

ingress:
  # -- Since the 15.0 version, this feature allows you to enable Ingress, a Kubernetes APi object, providing load balancing.
  enabled: false
  # -- Name of the IngressClass cluster resource to use.
  # e.g: azure/application-gateway
  className:
  # -- Additional annotations for the Ingress resource.
  # e.g:
  # annotations:
  #   appgw.ingress.kubernetes.io/backend-path-prefix: "/"
  #   appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 400, 404"
  #   appgw.ingress.kubernetes.io/health-probe-path: "/health"
  annotations: {}
  # -- Defines the Ingress host.
  host:
  # -- A path mapping that corresponds to the ICM backend. If left blank, the path
  # defaults to `/icm/*`.
  path:
  tls:
    # -- Enables HTTPS for ICM. TLS must be enabled for 'externalAccess' to work.
    enabled: true
    # -- The functionality of the 'secretName' parameter differs based on how you intend to provide a Kubernetes secret that stores the required certificate:
    # 1) If you create a Kubernetes TLS secret that stores the required certificate manually by yourself, enter the name of the secret in the 'secretName' parameter.
    #    To learn about Kubernetes TLS secrets, see Kubernetes documentation at https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets.
    # 2) If you intend to use the 'clusterIssuer' parameter to provide the required certificate, use the 'secretName' parameter to define a custom name for a secret that will be created by the cluster issuer.
    secretName:
    # -- Allows you to define the name of a cluster-issuer to be used for creating the certificate secret.
    # For more information about cluster issuer setup, see one of the following documentations based on which platform you use to deploy Inspire:
    # AKS (Application Gateway Kubernetes Ingress): https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/lets-encrypt/#certificate-issuance-with-letsencryptorg
    # EKS (NGINX Ingress): https://cert-manager.io/docs/tutorials/acme/ingress/
    clusterIssuer:


# -- Enables or disables the use of the onEveryStartupSettings object.
useEveryStartupSettings: false
# -- An object whose structure is the same as the structure of the initialServerSettings object.
# The object's settings are applied every time ICM starts.
onEveryStartupSettings:
  packageImportExport: {}
  passwordAccountPolicy: {}

# -- Enables or disables the use of the initialServerSettings object.
useInitialServerSettings: true
# -- An object whose settings are applied only once when ICM is initialized.
# The content of this object is transformed to JSON format and passed directly to ICM.
# Uncomment and configure the packageImportExport and passwordAccountPolicy settings.
# To learn about the settings' purpose see the Password and Account Policy Tab sections of Inspire Designer User Manual.
initialServerSettings:
  packageImportExport:
    overwriteExistingUsersOnImport: false
#    overwriteExistingGroupsAndSyncPointsOnImport: false
#    overwriteExistingApprovalStatesOnImport: false
#    overwriteServerPropertiesOnImport: false
  passwordAccountPolicy: {}
#    minimumLength: 3
#    alphabetCharacterRequired: false
#    numericCharacterRequired: false
#    specialCharacterRequired: false
#    mixedUppercaseAndLowercaseLettersRequired: false
#    differentUsernameAndPasswordRequired: false
#    expirationDays: 0
#    inactiveAccountExpirationDays: 0
#    minimumPasswordAgeInDays: 0.0
#    reuseLimit: 10
#    failedLoginAttemptsBeforeAccountLock: 6
#    accountLockTimeoutSeconds: 60

# -- Internal parameter
role: "icm"

# -- Learn about liveness probes at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/.
# Learn about the probe's configuration settings at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes.
livenessProbe:
  # -- Defines the delay before the ICM container liveness probe is initiated.
  initialDelaySeconds: 5
  # -- Defines how often to perform the ICM container probe.
  periodSeconds: 10
  # -- Defines when the ICM container probe times out.
  timeoutSeconds: 2
  # -- Defines the minimum consecutive failures for the ICM container probe to be considered failed after having succeeded.
  failureThreshold: 10
  # -- Defines the minimum consecutive successes for the ICM container probe to be considered successful after having failed.
  successThreshold: 1

# -- Learn about readiness probes at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/.
# Learn about the probe's configuration settings at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes.
readinessProbe:
  # -- Defines the delay before the ICM container readiness probe is initiated.
  initialDelaySeconds: 30
  # -- Defines how often to perform the ICM container probe.
  periodSeconds: 10
  # -- Defines when the ICM container probe times out.
  timeoutSeconds: 3
  # -- Defines the minimum consecutive failures for the ICM container probe to be considered failed after having succeeded.
  failureThreshold: 10
  # -- Defines the minimum consecutive successes for the ICM container probe to be considered successful after having failed
  successThreshold: 1

# -- A custom service account that runs the ICM pod.
# Also, you may need to create a service account when passing Secrets to Kubernetes from an external secret management system.
# In such a case, the service account must have the permissions to access the external system (e.g. AWS Secrets Manager).
existingServiceAccount: ""

podSecurityContext:
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod.
  runAsUser: 1001
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod.
  fsGroup: 1001
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod.
  runAsNonRoot: true
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-seccomp-profile-for-a-container.
  seccompProfile:
    type: RuntimeDefault
securityContext:
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container.
  readOnlyRootFilesystem: true
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container.
  privileged: false
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container.
  allowPrivilegeEscalation: false
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container.
  runAsUser: 1001
  # -- Learn about this setting at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container.
  # The default (recommended) configuration prohibits all Linux capabilities.
  capabilities:
    drop:
      - ALL

resources:
  requests:
    # -- Specifies the number of CPUs that an ICM container requests within its Kubernetes pod. Kubernetes uses CPU requests to find a machine that best fits the container.
    # It defines a minimum number of CPUs that the container may consume. If there is no contention for CPU, it may use as many CPUs as is available on the machine.
    # If there is CPU contention on the machine, CPU requests provide a relative weight across all containers on the system for how much CPU time the container may use.
    cpu: 2
    # -- Specifies the amount of memory required for an ICM container to run.
    # Even though each container is able to consume as much memory on the machine as possible, this parameter improves placement of pods in the cluster. Kubernetes then takes available memory into account prior to binding your pod to a machine.
    memory: 1Gi
  limits:
    # -- Defines the number of CPUs that an ICM container is limited to use within its Kubernetes pod.
    # CPU limits are used to control the maximum number of CPUs that the container may use independent of contention on the machine.
    # If a container attempts to use more than the specified limit, the system will throttle the container.
    # This allows your container to have a consistent level of service independent of the number of pods on the machine.
    cpu: 2
    # -- Defines the amount of memory an ICM container is limited to use.
    # If the container exceeds the specified memory limit, it will be terminated and potentially restarted depending on the container restart policy.
    memory: 1Gi

service:
  # -- Provide any additional annotations which may be required.
  annotations: {}
  # -- Defines the value for the service Kubernetes object.
  # It is recommended to keep the default value because it makes ICM accessible only from within the Kubernetes cluster.
  # The LoadBalancer value makes ICM accessible from the Internet. This should only be used for testing purposes. [ClusterIP/LoadBalancer]
  type: "ClusterIP"

deployment:
  # -- Provides the ability to customize ICM's deployment using Kubernetes annotations.
  annotations: {}

# -- Additional labels for ICM pods
podLabels: {}