# Default values for Hello.

# -- Number of Hello containers to deploy
replicaCount: 1

# NGINX-Demos Hello image
# ref: https://hub.docker.com/r/nginxdemos/hello
image:
  # -- Hello image repository
  repository: nginxdemos/hello
  # -- Override tag specified by `appVersion` in the chart file
  tag: 0.2
  # -- Hello image pull policy
  pullPolicy: IfNotPresent

# -- Hello image pull secrets
imagePullSecrets: []
# -- Partially override the name used for chart objects
nameOverride: ''
# -- Fully override the name used for chart objects
fullnameOverride: ''

## Hello service account parameters
serviceAccount:
  # -- Enable service account creation (will use `default` if false)
  create: false
  # -- Annotations to use with the service account
  annotations: {}
  # -- Force the name used for the service account
  name: ''

# -- Annotations for Hello pods
podAnnotations: {}

# -- Configure Hello pod security context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}

# -- Configure security context (main Hello container only)
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
securityContext: {}

# Hello service parameters
service:
  # -- Hello service type
  type: ClusterIP
  # -- Hello container port
  port: 80

# Configure the ingress resource that allows you to access the Hello application
# ref: https://kubernetes.io/docs/user-guide/ingress/
ingress:
  # -- Enable ingress record generation for Hello
  enabled: false
  # -- Type Ingress path type
  pathType: ImplementationSpecific
  # -- Force Ingress API version (automatically detected if not set)
  apiVersion: ''
  # -- Default host for the ingress record
  hostname: hello.local
  # -- Default path for the ingress record
  # NOTE: You may need to set this to '/*' in order to use this with ALB ingress controllers
  path: /
  # -- Additional annotations for the Ingress resource. To enable certificate autogeneration, place cert-manager annotations here.
  # For a full list of possible ingress annotations, please see
  # ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  # Use this parameter to set the required annotations for cert-manager, see
  # ref: https://cert-manager.io/docs/usage/ingress/#supported-annotations
  #
  # e.g:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: cluster-issuer-name
  annotations: {}
  # -- Enable TLS configuration for the host defined at `ingress.hostname` parameter
  # TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
  tls: false

# Hello container resource requirements
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Autoscaling parameters
autoscaling:
  # -- Enable auto-scaling for Hello
  enabled: false
  # -- Minimum number of replicas to deploy
  minReplicas: 1
  # -- Maximum number of replicas that can be deployed
  maxReplicas: 100
  # -- Target CPU utilization (percent) for each replica
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node labels for pod assignment
#ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Tolerations for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# NOTE: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when set
affinity: {}
