{{- if and .Values.global.automation.enabled .Values.ips.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "inspire.applicationName" . }}-ips-config
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  InspireProductionServer.config: |
    {{- .Values.ips.configFileContent | nindent 4 }}
{{- end }}