{{- if .Values.global.fts.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qar.applicationName" $ }}-fts
  namespace: {{ .Release.namespace | quote }}
  labels:
    {{- include "qar.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qar.labels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        {{- include "qar.labels" $ | nindent 8 }}
      name: {{ include "qar.applicationName" $ }}-fts-template
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "qar.serviceAccountName" $ }}
  {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
    {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
      initContainers:
      - name: {{ include "qar.applicationName" . }}-fts-init
        image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args: ["init"]
        volumeMounts:
          - name: work
            mountPath: /opt/qar/tmp
      - name: {{ include "qar.applicationName" . }}-fts-wait-ondemand
        image: "{{ .Values.global.wait.image.name }}:{{ .Values.global.wait.image.tag }}"
        imagePullPolicy: IfNotPresent
        args:
          - "pod"
          - "-lrole=ondemand"
      containers:
      - name: {{ include "qar.applicationName" . }}-fts
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: ARS_FTI_EXPORT_POLL_DELAY
          value: {{ .Values.exportPollDelay | quote }}
        {{ include "ondemand.env.library" . | nindent 8 }}
        {{ include "ondemand.env.database" . | nindent 8 }}
        {{ include "ondemand.env.user" . | nindent 8 }}
        ports:
          - name: http
            containerPort: 8191
        livenessProbe:
          exec:
            command: ["ps", "-p", "1"]
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
        readinessProbe:
          tcpSocket:
            port: 8191
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
        volumeMounts:
          - name: work
            mountPath: /opt/qar/tmp
      volumes:
      - name: restcfg
        emptyDir: {}
  {{- if .Values.persistence.enabled }}
    {{- if .Values.persistence.existingClaim }}
      - name: odpool
        persistentVolumeClaim:
          claimName: {{ tpl .Values.persistence.existingClaim $ }}
    {{- else }}
      - name: odpool
        emptyDir: {}
    {{- end }}
  {{- end }}
{{- end -}}
