{{- if .Values.global.sen.enabled }}
{{- $authorizationSecretName := printf "%s-%s-authorization-token" (include "inspire.applicationName" . ) .Values.role -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $authorizationSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-{{ .Values.role }}-authorization-token
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{ if $secret }}
  senAuthorizationToken: {{ $secret.data.senAuthorizationToken }}
  {{ else -}}
  senAuthorizationToken: {{ default (randAlphaNum 30) | b64enc }}
  {{- end }}
{{- end }}