{{- if .Values.global.scaler.enabled | and .Values.customEncryption.enabled }}
{{- $keys := required "Scaler custom encryption configuration is invalid. At least one custom key must be defined." .Values.customEncryption.keys}}
{{- $areDelegated := eq (include "inspire.secrets.areDelegated" (dict "secrets" $keys "sourceField" "keySource")) "true" }}
{{- if not $areDelegated }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler-custom-encryption-keys
  labels:
    app: {{ include "inspire.applicationName" . }}
    role: {{ .Values.role }}
data:
  {{- range $keys }}
  {{ .id }}: {{ (required "A key must have a value" .key) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}