{{- if .Values.global.scaler.enabled }}
{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.global.scaler.passOverrideSource) "true" }}
{{ $anythingToSave := (not $passDelegated)}}
{{- if $anythingToSave }}
{{- $scalerIcmSecretName := printf "%s-%s-icm" (include "inspire.applicationName" . ) .Values.role -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $scalerIcmSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-{{ .Values.role }}-icm
  labels:
    app: {{ include "inspire.applicationName" . }}
    role: {{ .Values.role }}
data:
  {{- if not $passDelegated }}
  {{ if $secret | and (.Values.global.scaler.passOverride | not) }}
  pass: {{ $secret.data.pass }}
  {{ else -}}
  pass: {{ .Values.global.scaler.passOverride | default (randAlphaNum 30) | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}