{{- if .Values.ingress.enabled | and .Values.global.scaler.enabled }}
{{ include "inspire.ingress.type.check" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler
  annotations:
    {{- include "inspire.scaler.ingress.annotations" . | indent 4 }}
    {{- with .Values.ingress.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.tls.enabled | and .Values.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "tls-secret-%s" .Values.ingress.host) }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ include "inspire.scaler.ingress.path" . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "inspire.applicationName" . }}-scaler
            port:
              number: {{ include "inspire.env.scaler.port" . }}
{{- end }}