{{- if eq "cluster" (.Values.installationType | trim | lower ) }}
{{- if .Values.autoscaling.enabled | or .Values.statefulScaling.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler-deployment-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    resourceNames:
      - {{ include "inspire.applicationName" . }}-scaler
    verbs: [ "get", "watch" ]
{{- end }}
{{- end }}