{{- if .Values.authentication.saml2.enabled }}
{{- $keystoreDelegated := eq (include "inspire.secret.isDelegated" .Values.authentication.saml2.keystoreSource) "true" }}
{{- $keystorePasswordDelegated := eq (include "inspire.secret.isDelegated" .Values.authentication.saml2.keystorePasswordSource) "true" }}
{{- $serviceProviderKeypairPassword := eq (include "inspire.secret.isDelegated" .Values.authentication.saml2.serviceProviderKeypairPasswordSource) "true" }}

{{ $anythingToSave := (not $keystorePasswordDelegated) | or (not $serviceProviderKeypairPassword) | or (not $keystoreDelegated)}}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler-saml
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
{{- if not $keystoreDelegated }}
  keystore: |-
{{ required "SAML keystore file content in base64 format is mandatory" .Values.authentication.saml2.keystore | indent 4 }}
{{- end }}
{{- if not $keystorePasswordDelegated }}
  keystorePassword: {{ required "SAML keystore password is mandatory" .Values.authentication.saml2.keystorePassword | b64enc }}
{{- end }}
{{- if not $serviceProviderKeypairPassword }}
  serviceProviderKeypairPassword: {{ required "SAML service provider keypair password is mandatory" .Values.authentication.saml2.serviceProviderKeypairPassword | b64enc }}
{{- end }}
{{- end }}
{{- end }}