{{- if .Values.global.sen.enabled }}
{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.sen.db.passSource) "true" }}
{{- $userDelegated := eq (include "inspire.secret.isDelegated" .Values.sen.db.userSource) "true" }}
{{- $connectionStringDelegated := eq (include "inspire.secret.isDelegated" .Values.sen.db.connectionStringSource) "true" }}

{{ $anythingToSave := (not $passDelegated) | or (not $userDelegated) | or (not $connectionStringDelegated) }}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler-sen-database
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{- if not $userDelegated }}
  dbUser: {{ required "Database user is mandatory" .Values.sen.db.user | b64enc }}
  {{- end }}
  {{- if not $passDelegated }}
  dbPass: {{ required "Database password is mandatory" .Values.sen.db.pass | b64enc }}
  {{- end }}
  {{- if not $connectionStringDelegated }}
  dbConnectionString: {{ required "Connection string is mandatory" .Values.sen.db.connectionString | b64enc }}
  {{ end }}
{{- end }}
{{- end }}