{{- if .Values.global.sen.enabled }}
{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.global.sen.passOverrideSource) "true" }}
{{- $senSecretName := printf "%s-%s-sen" (include "inspire.applicationName" . ) .Values.role -}}
{{ $anythingToSave := (not $passDelegated)}}
{{- if $anythingToSave }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $senSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-{{ .Values.role }}-sen
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{ if $secret | and (.Values.global.sen.passOverride | not) }}
  pass: {{ $secret.data.pass }}
  {{ else -}}
  pass: {{ .Values.global.sen.passOverride | default (randAlphaNum 30) | b64enc }}
  {{- end }}
{{- end }}
{{- end }}