{{- if empty .Values.existingServiceAccount }}
{{- if eq "cluster" (.Values.installationType | trim | lower ) }}
{{- if .Values.autoscaling.enabled | or .Values.statefulScaling.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inspire.applicationName" . }}-scaler
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}