apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inspire.applicationName" . }}-pod-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "inspire.applicationName" . }}-pod-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace | quote }}
