{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.db.passSource) "true" }}
{{- $userDelegated := eq (include "inspire.secret.isDelegated" .Values.db.userSource) "true" }}
{{- $connectionStringDelegated := eq (include "inspire.secret.isDelegated" .Values.db.connectionStringSource) "true" }}

{{ $anythingToSave := (.Values.db.pass | and (not $passDelegated)) | or (.Values.db.user | and (not $userDelegated)) | or (.Values.db.connectionString | and (not $connectionStringDelegated))}}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-icm-database
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{- if .Values.db.connectionString | and (not $connectionStringDelegated) }}
  dbConnectionString: {{ .Values.db.connectionString | b64enc }}
  {{- else }}
  {{- if not $userDelegated }}
  dbUser: {{ .Values.db.user | b64enc}}
  {{- end }}
  {{- if not $passDelegated }}
  dbPass: {{ .Values.db.pass | b64enc}}
  {{- end }}
  {{- end }}
{{- end }}