{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.global.icm.adminPassOverrideSource) "true" }}
{{ $anythingToSave := (not $passDelegated) }}
{{- if $anythingToSave }}

{{- $icmSecretName := printf "%s-icm" (include "inspire.applicationName" . ) -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $icmSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-icm
  labels:
    app: {{ include "inspire.applicationName" . }}
    role: icm
data:
  {{ if $secret | and (.Values.global.icm.adminPassOverride | not) -}}
  pass: {{ $secret.data.pass }}
  {{ else -}}
  pass: {{ .Values.global.icm.adminPassOverride | default (randAlphaNum 30) | b64enc }}
  {{ end }}
{{ end }}