apiVersion: v1
kind: Service
metadata:
  name: {{ include "inspire.applicationName" . }}-icm
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
  annotations:
    description: Service for ICM
{{- with .Values.service.annotations }}
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
spec:
  ports:
    - name: {{ include "inspire.applicationName" . }}-icm-port
      port: {{ include "inspire.env.icm.port" . }}
      targetPort: 30353
{{- if .Values.externalAccess.enabled }}
    - name: {{ include "inspire.applicationName" . }}-icm-http
      port: 8080
      targetPort: 8080
{{- end }}
  selector:
        {{- include "inspire.labels" . | nindent 4 }}
  type: {{ .Values.service.type }}
