apiVersion: v2
appVersion: 0.3.19
dependencies:
  - name: mongodb
    version: 13.15.5
    repository: https://charts.bitnami.com/bitnami
description: A Helm chart to deploy the Document Host (Docuhost) demo service
name: docuhost
type: application
version: 0.1.27
