# Global values for QAR

global:
  # -- Defines a unique name of an application within a Kubernetes namespace.
  applicationName: "qar"
  # -- List of image repository pull secrets. Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # Example:
  # imagePullSecrets:
  #   - name: myRegistryKeySecretName
  imagePullSecrets: []
  # -- Enter the name of an existing service account to use. Otherwise, one will be created by default.
  existingServiceAccount: ""
  ondemand:
    image:
      # -- Defines the URL address of the QAR server image stored in a container repository.
      name: registry.sptcloud.com/qar/ondemand
      # -- Overrides tag specified by the `appVersion` in the chart file.
      tag: 10.5.0.5-oracle-ubi-8.8-854
      # -- QAR image pull policy [Always|IfNotPresent].
      pullPolicy: IfNotPresent
    # -- Used in the header line of the `ars.ini` file to identify the name of the CMOD instance.
    odInstanceName: ARCHIVE
    # -- Identifies the name of the CMOD database (will be lower-cased for database creation).
    # If not provided, the name `archive` will be used.
    serverInstanceName: ARCHIVE
    # -- Determines whether the server program is linked to a cache-only storage manager or an
    # archive storage manager. Required on library servers. [TSM|NO_TSM|CACHE_ONLY]
    storageManager: NO_TSM
    trace:
      # -- Enables the system trace facility
      enabled: false
    db:
      # -- Specifies the DBMS used by the Library Server [DB2|ORACLE].
      engine: ORACLE
      # -- Defines the Oracle TNS service name for the CMOD database. If left undefined, the
      # lower-cased `serverInstanceName` value is used.
      tnsServiceName: ""
      # -- Determines the number of processes that CMOD starts on the library server to
      # handle connections to the database. Specify a value that supports the peak number
      # of concurrent database connections library server needs to handle.
      numSubServers: 10
      # -- Defines (in plain text) the name of the administrative user to be created in the oracled
      # database(s). If left undefined, the default user `archive` is created. Use the `userOverrideSource`
      # variable to define the username using a Secret.
      userOverride: ""
      # -- Uses a Secret to define the administrative user to be created in the Oracle database(s).
      userOverrideSource:
        useSecret: false
        secretName: ""
        secretKey: ""
      # -- Defines (in plain text) the password of the administrative user to be created in the
      # Oracle database(s). If left undefined, the deployment will generate a random alphanumeric
      # password. Use the `passwordOverrideSource` variable to define the password using an existing Secret.
      passwordOverride: ""
      # -- Uses a Secret to define the password of the administrative user to be created in the
      # Oracle database(s).
      passwordOverrideSource:
        useSecret: false
        secretName: ""
        secretKey: ""
    # -- Defines (in plain text) the name of the CMOD admin user. If left undefined, the default user
    # `admin` is created. Use the `userOverrideSource` variable to define the username using an existing Secret.
    userOverride: ""
    # -- Uses a Secret to define the CMOD admin user.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the password of the CMOD admin user. If left undefined, the deployment
    # will generate a random alphanumeric password. Use the `passwordOverrideSource` variable to
    # define the password using an existing Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the CMOD administrative user's password.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines the port to run the ARS listener on. If left undefined, the default port 1445 is used.
    portOverride:
  restapi:
    # -- Defines whether to deploy a REST API server.
    enabled: false
    image:
      # -- Defines the URL address of the REST API server image stored in a container repository.
      name: registry.sptcloud.com/qar/ondemand-restapi
      # -- Overrides tag specified by the `appVersion` in the chart file.
      tag: 10.5.0.5-liberty-23.0.0.5
      # -- QAR REST API image pull policy [Always|IfNotPresent].
      pullPolicy: IfNotPresent
    # -- Defines (in plain text) the name of the CMOD user (consumer) to use when generating the REST configuration
    # (OD access pool). If left undefined, the default user `admin` is used. Use the `userOverrideSource`
    # variable to define the username using a Secret.
    userOverride: ""
    # -- Uses a Secret to define the CMOD REST API user (consumer) used when generating the REST configuration.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the password of the CMOD user (consumer) to use when generating the REST configuration
    # (OD access pool). If left undefined, the deployment will generate a random alphanumeric password. Use
    # the `passwordOverrideSource` variable to define the user name using an existing Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the CMOD REST API user's (consumer's) password.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines the port to run the HTTP listener on. If left undefined, the default port 9080 is used.
    portOverride:
  arsload:
    # -- Defines whether to deploy an ARSLOAD server.
    enabled: false
    image:
      # -- Defines the URL address of the ARSLOAD server image stored in a container repository.
      name: registry.sptcloud.com/qar/ondemand
      # -- Overrides tag specified by the `appVersion` in the chart file.
      tag: 10.5.0.5-oracle-ubi-8.8-854
      # -- QAR REST API image pull policy [Always|IfNotPresent].
      pullPolicy: IfNotPresent
    # -- Defines (in plain text) the name of the CMOD ARSLOAD user (for batch-loading documents).
    # If left undefined, the default user `admin` is used. Use the `userOverrideSource` variable
    # to define the username using a Secret.
    userOverride: ""
    # -- Uses a Secret to define the CMOD ARSLOAD user.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the password of the CMOD ARSLOAD user (for batch-loading documents).
    # If left undefined, the deployment will generate a random alphanumeric password. Use the
    # `passwordOverrideSource` variable to define the user name using an existing Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the CMOD ARSLOAD user's password.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
  fts:
    # -- Defines whether to enable Full-Text Search.
    enabled: false
    image:
      # -- Defines the URL address of the FTS server image stored in a container repository.
      name: registry.sptcloud.com/qar/ondemand-fts
      # -- Overrides tag specified by the `appVersion` in the chart file.
      tag: 10.5.0.5-ubi-8.8-854
      # -- FTS image pull policy [Always|IfNotPresent].
      pullPolicy: IfNotPresent
    # -- Defines the port to run the FTS server on. If left undefined, the default port 8191 is used.
    portOverride:
  navigator:
    # -- Defines whether to deploy a Content Navigator server. [Not Implemented Yet]
    enabled: false
    # -- Defines the port to run the HTTP listener on. If left undefined, the default port 9080 is used. [Not Implemented Yet]
    portOverride:
  zookeeper:
    # -- Use Zookeeper to manage locking between multiple active CMOD server
    # server instances. This should be set to `true` when `replicaCount` > 1.
    enabled: false
    # -- Comma-separated list of Zookeeper servers to use. For example,
    # serverList: zoo1.example.com:2181,zoo2.example.com:2181
    serverList: ""
    # -- Defines (in plain text) the name of the Zookeeper user.
    # If left undefined, the default user `admin` is used. Use the `userOverrideSource` variable
    # to define the username using a Secret.
    userOverride: ""
    # -- Uses a Secret to define the Zookeeper user.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the Zookeeper user's password.
    # If left undefined, the deployment will generate a random alphanumeric password. Use the
    # `passwordOverrideSource` variable to define the password using a Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the Zookeeper user's password.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
  # Learn about k8s-wait-for at https://github.com/groundnuty/k8s-wait-for
  wait:
    image:
      # -- Defines the name of the k8s-wait-for image stored in a container repository.
      name: ghcr.io/groundnuty/k8s-wait-for
      # -- Specifies the version tag to use.
      tag: no-root-v2.0
