# Global values for QAR

global:
  # -- Defines a unique name of an application within a Kubernetes namespace.
  applicationName: "qar"
  # -- List of image repository pull secrets. Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # Example:
  # imagePullSecrets:
  #   - name: myRegistryKeySecretName
  imagePullSecrets: []
  oracledb:
    # -- Defines (in plain text) the password to be created for the Oracle database's SYS user.
    # If left undefined, the deployment will generate a random alphanumeric password. Use the
    # 'passwordOverrideSource' variable to define the password using a Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the password of the CMOD user to be created in the Oracle database(s).
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    tnsListener:
      # -- Defines the port to run the TNS listener on. If left undefined, the default port 1521 is used.
      portOverride:
    emExpress:
      # -- Defines the port to run the EM Express app on. If left undefined, the default port 5500 is used.
      portOverride:
  ondemand:
    db:
      # -- Defines (in plain text) the name of the administrative user to be created in the oracled
      # database(s). If left undefined, the default user `archive` is created. Use the `userOverrideSource'
      # variable to define the username using a Secret.
      userOverride: ""
      # -- Uses a Secret to define the administrative user to be created in the Oracle database(s).
      userOverrideSource:
        useSecret: false
        secretName: ""
        secretKey: ""
      # -- Defines (in plain text) the password of the administrative user to be created in the
      # Oracle database(s). If left undefined, the deployment will generate a random alphanumeric
      # password. Use the 'passwordOverrideSource' variable to define the password using a Secret.
      passwordOverride: ""
      # -- Uses a Secret to define the password of the administrative user to be created in the
      # Oracle database(s).
      passwordOverrideSource:
        useSecret: false
        secretName: ""
        secretKey: ""
    # -- Defines (in plain text) the name of the CMOD admin user. If left undefined, the default user
    # `admin` is created. Use the `userOverrideSource' variable to define the username using a Secret.
    userOverride: ""
    # -- Uses a Secret to define the CMOD admin user.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the password of the CMOD admin user. If left undefined, the deployment
    # will generate a random alphanumeric password. Use the 'passwordOverrideSource' variable to
    # define the password using a Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the password of the CMOD user.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines the port to run the ARS listener on. If left undefined, the default port 1445 is used.
    portOverride:
  restapi:
    # -- Defines whether to deploy a REST API server.
    enabled: false
    # -- Defines (in plain text) the name of the CMOD user to use when generating the REST configuration
    # (OD access pool). If left undefined, the default user `admin` is used. Use the `userOverrideSource'
    # variable to define the username using a Secret.
    userOverride: ""
    # -- Uses a Secret to define the CMOD user used when generating the REST configuration.
    userOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines (in plain text) the password of the CMOD user to use when generating the REST configuration
    # (OD access pool). If left undefined, the deployment will generate a random alphanumeric password. Use
    # the 'passwordOverrideSource' variable to define the username using a Secret.
    passwordOverride: ""
    # -- Uses a Secret to define the password of the CMOD user used when generating the REST configuration.
    passwordOverrideSource:
      useSecret: false
      secretName: ""
      secretKey: ""
    # -- Defines the port to run the HTTP listener on. If left undefined, the default port 9080 is used.
    portOverride:
  fts:
    # -- Defines whether to enable Full-Text Search.
    enabled: false
    # -- Defines the port to run the FTS serverr on. If left undefined, the default port 8191 is used.
    portOverride:
  navigator:
    # -- Defines whether to deploy a Content Navigator server.
    enabled: false
    # -- Defines the port to run the HTTP listener on. If left undefined, the default port 9080 is used.
    portOverride:
  arsload:
    # -- Defines whether to deploy an ARSLOAD server.
    enabled: false
  zookeeper:
    # -- Defines whether to deploy a Zookeeper instance.
    enabled: false
    # -- Defines the port to run the Zookeeper listener on.
    # If left undefined, the default port 1445 is used.
    portOverride:
