{{- if (include "docuhost.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "docuhost.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
data:
  app-env: {{ required "A value for 'app.env' is required." .Values.app.env | quote }}
  app-url: {{ required "A value for 'app.url' is required." .Values.app.url | quote }}
  auth-trust-host: {{ required "A value for 'auth.trustHost' is required." .Values.auth.trustHost | quote }}
  auth0-audience: {{ required "A value for 'auth.auth0.audience' is required." .Values.auth.auth0.audience | quote }}
  auth0-issuer: {{ required "A value for 'auth.auth0.issuer' is required." .Values.auth.auth0.issuer | quote }}
  db-protocol: {{ .Values.db.protocol | default "mongodb" | quote }}
  db-host: {{ .Values.db.host | default "localhost" | quote }}
  db-port: {{ .Values.db.port | default "" | quote }}
  db-name: {{ .Values.db.name | default "documents" | quote }}
  shortlink-domain: {{ required "A value for 'shortlink.domain' is required." .Values.shortlink.domain | quote }}
  shortlink-serviceUrl: {{ required "A value for 'shortlink.serviceUrl' is required." .Values.shortlink.serviceUrl | quote }}
{{- end }}
