{{- if (include "docuhost.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "docuhost.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
data:
  app-env: {{ required "A value for 'app.env' is required." .Values.app.env | quote }}
  app-url: {{ required "A value for 'app.url' is required." .Values.app.url | quote }}
  auth0-audience: {{ required "A value for 'auth0.audience' is required." .Values.auth0.audience | quote }}
  auth0-domain: {{ required "A value for 'auth0.domain' is required." .Values.auth0.domain | quote }}
  db-host: {{ required "A value for 'db.host' is required." .Values.db.host | quote }}
  db-port: {{ required "A value for 'db.port' is required." .Values.db.port | quote }}
  db-name: {{ required "A value for 'db.name' is required." .Values.db.name | quote }}
  shortlink-domain: {{ required "A value for 'shortlink.domain' is required." .Values.shortlink.domain | quote }}
  shortlink-serviceUrl: {{ required "A value for 'shortlink.serviceUrl' is required." .Values.shortlink.serviceUrl | quote }}
{{- end }}
