{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docuhost.mongodb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.containerPort }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector: {{- include "docuhost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
