{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docuhost.mongodb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default (randAlphaNum 16) | b64enc | quote }}
  mongodb-password: {{ required "A value for 'db.password' is required." .Values.db.password | b64enc | quote }}
{{- end }}
