apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "docuhost.fullname" . }}-pod-reader
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "docuhost.fullname" . }}-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "docuhost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
