{{- if (include "docuhost.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docuhost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
type: Opaque
data:
  auth0-client-id: {{ required "A value for 'auth0.clientId' is required." .Values.auth0.clientId | b64enc | quote }}
  auth0-client-secret: {{ required "A value for 'auth0.clientSecret' is required." .Values.auth0.clientSecret | b64enc | quote }}
  auth0-public-key: {{ required "A value for 'auth0.publicKey' is required." .Values.auth0.publicKey | b64enc | quote }}
  db-username: {{ required "A value for 'db.username' is required." .Values.db.username | b64enc | quote }}
  db-password: {{ required "A value for 'db.password' is required." .Values.db.password | b64enc | quote }}
  shortlink-apiKey: {{ required "A value for 'shortlink.apiKey' is required." .Values.shortlink.apiKey | b64enc | quote }}
{{- end  }}
