{{- if (include "docuhost.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docuhost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "docuhost.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ required "A value for 'db.username' is required." .Values.db.username | b64enc | quote }}
  db-password: {{ required "A value for 'db.password' is required." .Values.db.password | b64enc | quote }}
  shortlink-apikey: {{ required "A value for 'shortlink.apikey' is required." .Values.shortlink.apikey | b64enc | quote }}
{{- end  }}
