{{- if (include "docuhost.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docuhost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
type: Opaque
data:
  auth-secret: {{ required "A value for 'auth.secret' is required." .Values.auth.secret | b64enc | quote }}
  auth0-id: {{ required "A value for 'auth.auth0.id' is required." .Values.auth.auth0.id | b64enc | quote }}
  auth0-secret: {{ required "A value for 'auth.auth0.secret' is required." .Values.auth.auth0.secret | b64enc | quote }}
  db-username: {{ .Values.db.username | default "docuhost" | b64enc | quote }}
  db-password: {{ required "A value for 'db.password' is required." .Values.db.password | b64enc | quote }}
  shortlink-apiKey: {{ required "A value for 'shortlink.apiKey' is required." .Values.shortlink.apiKey | b64enc | quote }}
{{- end  }}
