{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docuhost.serviceAccountName" . }}
  labels: {{- include "docuhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: docuhost
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- .Values.serviceAccount.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
