{{- if eq .Values.architecture "replicated" -}}
{{- $fullname := include "oracledb.fullname" . -}}

{{- range $index := until (.Values.replicaCount | int) -}}
{{- $targetPod := printf "%s-%d" $fullname $index -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $targetPod }}
  namespace: {{ include "oracledb.namespace" $ | quote }}
  labels: {{- include "oracledb.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: oracledb
    {{- if $.Values.commonLabels }}
    {{ include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or $.Values.service.annotations $.Values.commonAnnotations }}
  annotations:
  {{- if $.Values.service.annotations }}
  {{- include "common.tplvalues.render" ( dict "value" $.Values.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: oracledb
      port: {{ $.Values.service.ports.oracledb | default 1521 }}
      targetPort: oracledb
    - name: emexpress
      port: {{ $.Values.service.ports.emexpress | default 5500 }}
      targetPort: emexpress
  selector: {{- include "oracledb.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: oracledb
    statefulset.kubernetes.io/pod-name: {{ $targetPod }}
---
{{- end -}}
{{- end -}}
