apiVersion: v2
appVersion: "17.4"
description: Inspire
name: inspire
type: application
version: 1.0.0
annotations:
  com.quadient.spt.refarch.upstream-chart-version: "4.0.0"
  org.opencontainers.image.source: "https://github.com/robertwtucker/spt-charts"
dependencies:
  - name: automation
    version: "4.0.0"
    repository: "file://charts/automation"
  - name: icm
    version: "4.0.0"
    repository: "file://charts/icm"
  - name: interactive
    version: "4.0.0"
    repository: "file://charts/interactive"
  - name: scaler
    version: "4.0.0"
    repository: "file://charts/scaler"
