{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "scaler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "scaler.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass -}}
  {{- if (eq "-" .Values.persistence.storageClass) -}}
  {{ printf "storageClassName: \"\"" -}}
  {{- else }}
  {{ printf "storageClassName: %s" .Values.persistence.storageClass -}}
  {{- end -}}
  {{- end -}}
{{- end }}
