{{- if .Values.restapi.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qar.fullname" . }}-restapi
  namespace: {{ include "qar.namespace" . | quote }}
  labels: {{- include "qar.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: restapi
    {{- if .Values.commonLabels }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.restapi.ingress.annotations .Values.commonAnnotations }}
  annotations:
  {{- if .Values.restapi.ingress.annotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.restapi.ingress.annotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.restapi.ingress.tls.enabled }}
  tls:
    {{- if .Values.restapi.ingress.tls.hosts }}
    - hosts:
      {{- range .}}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts}}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.restapi.ingress.paths.http.path }}
            pathType: {{ $.Values.restapi.ingress.paths.http.pathType }}
            backend:
              serviceName: {{ include "qar.fullname" $ }}-restapi
              servicePort: {{ $.Values.restapi.service.ports.http }}
    {{- end }}
  {{- end }}
{{- end -}}
