{{- if .Values.global.automation.enabled }}

{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.db.passSource) "true" }}
{{- $userDelegated := eq (include "inspire.secret.isDelegated" .Values.db.userSource) "true" }}

{{ $anythingToSave := (not $passDelegated) | or (not $userDelegated) }}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-automation-database
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{- if not $userDelegated }}
  dbUser: {{ required "Database user is mandatory" .Values.db.user | b64enc }}
  {{- end }}
  {{- if not $passDelegated }}
  dbPass: {{ required "Database password is mandatory" .Values.db.pass | b64enc }}
  {{- end }}
{{- end }}
{{- end }}