{{- if .Values.global.interactive.enabled | and .Values.customEncryption.enabled }}
{{- $keys := (required "Interactive custom encryption configuration is invalid. At least one custom key must be defined." .Values.customEncryption.keys)}}
{{- $areDelegated := eq (include "inspire.secrets.areDelegated" (dict "secrets" $keys "sourceField" "keySource")) "true" }}
{{- if not $areDelegated }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-interactive-custom-encryption-keys
  labels:
    app: {{ include "inspire.applicationName" . }}
    role: {{ .Values.role }}
data:
  {{- range $keys }}
  {{ .id }}: {{ (required "The 'key' field must be defined in order to use custom encryption" .key ) | b64enc }}
  {{- end }}
{{- end }}
{{- end }}