{{- if .Values.global.interactive.enabled }}

{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.db.passSource) "true" }}
{{- $userDelegated := eq (include "inspire.secret.isDelegated" .Values.db.userSource) "true" }}
{{- $connectionStringDelegated := eq (include "inspire.secret.isDelegated" .Values.db.connectionStringSource) "true" }}

{{ $anythingToSave := (not $passDelegated) | or (not $userDelegated) | or (.Values.db.connectionString | and (not $connectionStringDelegated))}}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-interactive-database
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{- if not $userDelegated }}
  dbUser: {{ required "Database user is mandatory" .Values.db.user | b64enc }}
  {{- end }}
  {{- if not $passDelegated }}
  dbPass: {{ required "Database password is mandatory" .Values.db.pass | b64enc }}
  {{- end }}
  {{- if .Values.db.connectionString | and (not $connectionStringDelegated) }}
  dbConnectionString: {{ .Values.db.connectionString | b64enc }}
  {{- end }}
{{- end }}
{{- end }}