{{- if .Values.global.interactive.enabled | and .Values.fulltext | and .Values.fulltext.enabled }}
{{- $userDelegated := eq (include "inspire.secret.isDelegated" .Values.fulltext.usernameSource) "true" }}
{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.fulltext.passwordSource) "true" }}

{{ $anythingToSave := (not $passDelegated) | or (not $userDelegated) }}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-interactive-elasticsearch
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  {{- if not $userDelegated }}
  esUser: {{ .Values.fulltext.username | b64enc }}
  {{- end }}
  {{- if not $passDelegated }}
  esPass: {{ .Values.fulltext.password | b64enc }}
  {{- end }}
{{- end }}
{{- end }}