{{- if .Values.global.interactive.enabled }}
{{- $passDelegated := eq (include "inspire.secret.isDelegated" .Values.global.interactive.passOverrideSource) "true" }}
{{- $anythingToSave := (not $passDelegated) }}
{{- if $anythingToSave }}
{{- $interactiveIcmSecretName := printf "%s-%s-icm" (include "inspire.applicationName" . ) .Values.role -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $interactiveIcmSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-interactive-icm
  labels:
    app: {{ include "inspire.applicationName" . }}
    role: {{ .Values.role }}
data:
  {{ if $secret | and (.Values.global.interactive.passOverride | not)  -}}
  pass: {{ $secret.data.pass }}
  {{ else -}}
  pass: {{ .Values.global.interactive.passOverride | default (randAlphaNum 30) | b64enc }}
  {{ end}}
{{- end }}
{{- end }}