{{- if and .Values.global.interactive.enabled .Values.configurationXml }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "inspire.applicationName" . }}-interactive-configuration-xml
  labels:
    {{- include "inspire.labels" . | nindent 4 }}
data:
  configuration.xml: |
    {{- .Values.configurationXml | nindent 4}}
{{- end }}
