{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oracledb.applicationName" . }}-oracledb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "oracledb.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /oracle/*
        pathType: ImplementationSpecific
        backend:
          serviceName: {{ include "oracledb.applicationName" . }}-oracledb
          servicePort: 1521
      - path: /em/*
        pathType: ImplementationSpecific
        backend:
          serviceName: {{ include "oracledb.applicationName" . }}-emexpress
          servicePort: 5500
{{- end -}}
