{{- if not .Values.passwordSource.useSecret -}}
{{- $password := .Values.password | default (randAlphaNum 30) | b64enc -}}
{{- $secret := (lookup "v1" "Secret" (include "oracledb.namespace" .) (include "oracledb.fullname" .)) -}}
{{- if $secret -}}
{{- $password = index $secret.data "password" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracledb.fullname" . }}
  namespace: {{ include "oracledb.namespace" . | quote }}
  labels: {{- include "oracledb.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: oracledb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  password: {{ $password }}
{{- end -}}

