{{- if not .Values.passwordSource.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracledb.applicationName" . }}-oracledb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "oracledb.labels" . | nindent 4 }}
data:
  password: {{ .Values.password | default (randAlphaNum 30) | b64enc }}
{{- end -}}

