apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oracledb.applicationName" . }}-oracledb-setup
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "oracledb.labels" . | nindent 4 }}
data:
  01-patch-listener.sh: |
    #!/bin/bash

    echo "** Patching Oracle-Net Listener -> legacy client compatibility for CMOD"
    echo "USE_SID_AS_SERVICE_listener=on" >> /opt/oracle/homes/OraDB21Home1/network/admin/listener.ora
    lsnrctl reload
    echo "** Done."
  02-create-archive-pdb.sql: |
    CREATE PLUGGABLE DATABASE archive
    ADMIN USER archive IDENTIFIED BY "Password12345*"
    FILE_NAME_CONVERT=('/opt/oracle/oradata/ORCLCDB/pdbseed','/opt/oracle/oradata/ORCLCDB/archive');
  03-open-archive-pdb.sql: |
    ALTER PLUGGABLE DATABASE archive OPEN READ WRITE;
  04-save-archive-pdb.sql: |
    ALTER PLUGGABLE DATABASE archive SAVE STATE;
  05-create-navigator-pdb.sql: |
    CREATE PLUGGABLE DATABASE navigator
    ADMIN USER archive IDENTIFIED BY "Password12345*"
    FILE_NAME_CONVERT=('/opt/oracle/oradata/ORCLCDB/pdbseed','/opt/oracle/oradata/ORCLCDB/navigator');
  06-open-navigator-pdb.sql: |
    ALTER PLUGGABLE DATABASE navigator OPEN READ WRITE;
  07-save-navigator-pdb.sql: |
    ALTER PLUGGABLE DATABASE navigator SAVE STATE;
  08-archive-grant-perms.sql: |
    ALTER SESSION SET CONTAINER = archive;

    --
    -- Create Content Manager OnDemand role : ONDEMAND
    --
    DROP ROLE ONDEMAND;
    CREATE ROLE ONDEMAND;
    -- Database
    grant SELECT ANY DICTIONARY to ONDEMAND;
    -- Session
    grant CREATE SESSION to ONDEMAND;
    -- Tablespaces
    grant CREATE TABLESPACE to ONDEMAND;
    grant DROP TABLESPACE to ONDEMAND;
    -- Tables
    grant ALTER ANY TABLE to ONDEMAND;
    grant BACKUP ANY TABLE to ONDEMAND;
    grant CREATE TABLE to ONDEMAND;
    grant DELETE ANY TABLE to ONDEMAND;
    grant DROP ANY TABLE to ONDEMAND;
    grant INSERT ANY TABLE to ONDEMAND;
    grant LOCK ANY TABLE to ONDEMAND;
    grant SELECT ANY TABLE to ONDEMAND;
    grant UPDATE ANY TABLE to ONDEMAND;
    -- Indexes
    grant CREATE ANY INDEX to ONDEMAND;
    grant DROP ANY INDEX to ONDEMAND;

    --
    -- Grant role & permissions to ARCHIVE user
    ---
    grant ONDEMAND to ARCHIVE;
    grant UNLIMITED TABLESPACE to ARCHIVE;
