{{- if and .Values.setupScriptContent (not .Values.setupConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oracledb.applicationName" . }}-oracledb-setup
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "oracledb.labels" . | nindent 4 }}
data:
{{- .Values.setupScriptContent | nindent 2 }}
{{- end }}
