{{- $primaryDelegated := eq (include "inspire.secret.isDelegated" .Values.global.license.serverSource) "true" }}
{{- $secondaryDelegated := eq (include "inspire.secret.isDelegated" .Values.global.license.server2Source) "true" }}
{{ $anythingToSave := (not $primaryDelegated) | or (and (not $secondaryDelegated) (not (empty .Values.global.license.server2))) }}
{{- if $anythingToSave }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspire.applicationName" . }}-license
  labels:
    app: {{ include "inspire.applicationName" . }}
data:
  {{- if not $primaryDelegated }}
  cxLicServer: {{ (required "License server must not be empty" .Values.global.license.server) | b64enc }}
  {{- end }}
  {{- if not (empty .Values.global.license.server2) | and (not $secondaryDelegated) }}
  cxLicServer2: {{ .Values.global.license.server2 | b64enc }}
  {{- end }}
{{- end }}