{{- if .Values.global.restapi.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "qar.applicationName" . }}-{{ .Values.role }}
  labels:
    {{- include "qar.labels" . | nindent 4 }}
{{- end -}}
